---
- name: Nginx | Install the nginx repository
  sudo: yes
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present
  tags: nginx

- name: Nginx | Install nginx
  sudo: yes
  yum: name=nginx state=latest
  notify:
    - Nginx | Start nginx
  tags: nginx

- name: Nginx | Create the sites-available directory
  sudo: yes
  file: path=/etc/nginx/sites-available owner=root group=root state=directory
  tags: nginx

- name: Nginx | Create the sites-enabled directory
  sudo: yes
  file: path=/etc/nginx/sites-enabled owner=root group=root state=directory
  tags: nginx

- name: Nginx | Save original configuration
  sudo: yes
  command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.orginal creates=/etc/nginx/nginx.conf.orginal
  tags: nginx

- name: Nginx | Setup configuration
  sudo: yes
  template: src=nginx.conf dest=/etc/nginx/
  notify:
    - Nginx | Restart nginx
  tags: nginx
