---
- name: Nginx | Start nginx
  sudo: yes
  service: name=nginx state=started enabled=yes
  tags: nginx

- name: Nginx | Restart nginx
  sudo: yes
  service: name=nginx state=restarted
  tags: nginx

- name: Nginx | Reload nginx
  sudo: yes
  service: name=nginx state=reloaded
  tags: nginx
